services:
  orthanc-index-db:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  minio:
    image: bitnami/minio
    restart: unless-stopped
    ports:
      - 9000
      - 9001
    volumes:
      - minio_data:/wsi-storage
    environment:
      - MINIO_ROOT_USER=demo
      - MINIO_ROOT_PASSWORD=demodemo
      - MINIO_URL=minio:9000

  orthanc:
      image: osimis/orthanc
      restart: unless-stopped
      depends_on:
        - orthanc-index-db
        - minio
      ports:
        - 8042
      volumes:
        - orthanc_data:/var/lib/orthanc/db:Z
      env_file:
        - ../env/orthanc.env

volumes:
  minio_data:
  postgres_data:
  orthanc_data: